### ISSUE TITLE
Could not find module ‘Language.Haskell.TH.Datatype.TyVarBndr’

### ISSUE THREAD

**Issue by ocharles** [fpco/th-utilities#15]
I'm getting

```
src/TH/Utilities.hs:16:1: error:

    Could not find module ‘Language.Haskell.TH.Datatype.TyVarBndr’

    Perhaps you meant

      Language.Haskell.TH.Datatype.Internal

      Language.Haskell.TH.Datatype (from th-abstraction-0.3.2.0)

    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
```

when trying to build 0.2.4.2 on GHC 8.10.3. I have a feeling 0.2.4.2 now _only_ works on GHC 9.

**Comment by mgsloan** [comment]
Hmm, how are you building it?  That module is provided by the
th-abstraction package, a dependency which was added
in 574882efb9846ca487744f45acfb382e0bad7f09 .  Perhaps the cabal file needs
to be regenerated from the package.yaml?

**Comment by ocharles** [comment]
It was only added in https://hackage.haskell.org/package/th-abstraction-0.4.0.0 and there are no bounds specified, so I imagine I was trying to build with an older `th-abstraction`. I just tried adding `constraint: th-abstraction ^>= 0.4.0.0` to my `cabal.project`, but that's not a valid plan. Maybe it's worth adding some minimum bounds?

**Comment by mgsloan** [comment]
Ah, I see!  I've added the lower bound constraint in a hackage revision and in version 0.2.4.3

I suppose it is not a valid plan because of some upper bounds that can presumably be loosened? https://packdeps.haskellers.com/reverse/th-abstraction
