### ISSUE TITLE
GHC 8.10 compatibility

### ISSUE THREAD

**Issue by csabahruska** [fpco/th-utilities#9]
It does not compile with GHC 8.10. Could you please update the code?
I need it for `store`.

**Comment by sjakobi** [comment]
Indeed, an update would be much appreciated! :)

There's a [patch](https://gitlab.haskell.org/ghc/head.hackage/-/blob/d371b1e8c3316d1a6c3f39ec7ef3fe0805cb5256/patches/th-utilities-0.2.3.1.patch) available in head.hackage, although it doesn't seem to address the missing `liftTyped` method for `ExpLifter`:

```
src/TH/Utilities.hs:157:10: warning: [-Wmissing-methods]
    • No explicit implementation for
        ‘liftTyped’
    • In the instance declaration for ‘Lift ExpLifter’
    |
157 | instance Lift ExpLifter where
    |          ^^^^^^^^^^^^^^
```

**Comment by mgsloan** [comment]
Ah, thanks for pinging about this.  I've pushed and uploaded a new version, `0.2.4.0`, which builds with

```yaml
resolver: lts-14.17
compiler: ghc-8.10
allow-newer: true
extra-deps:
- primitive-0.7.0.1
```

Solution for `liftTyped` is to have it throw an exception. `ExpLifter` deviates from what's usually expected of `Lift`, and so the type of `liftTyped` didn't fit.
